/**
 * Methods Worksheet Builder
 *
 * Creates the Methods worksheet with documentation and warnings.
 */

import type ExcelJS from 'exceljs';

import { addWorksheet } from '../workbook.js';

/**
 * Build the Methods worksheet with documentation and warnings.
 */
export function buildMethodsSheet(workbook: ExcelJS.Workbook, warnings: string[]): void {
  // Create worksheet
  const worksheet = addWorksheet(workbook, {
    name: 'Methods',
    type: 'methods',
  });

  // Set up columns
  worksheet.getColumn(1).width = 100;

  let row = 1;

  // Title
  const titleCell = worksheet.getCell(row, 1);
  titleCell.value = 'ValueRank Export - Methodology Documentation';
  titleCell.font = { bold: true, size: 14 };
  row += 2;

  // Statistics explanation
  const sections = [
    {
      title: 'Mean Score Calculation',
      content:
        'The mean score is calculated as the arithmetic average of all numeric decision codes for each model. ' +
        'Decision codes are typically on a 1-5 scale where 1 indicates one value priority and 5 indicates the opposite.',
    },
    {
      title: 'Standard Deviation',
      content:
        'Standard deviation measures the spread of decision codes around the mean. ' +
        'Higher values indicate more variable responses. Calculated using the sample standard deviation formula (n-1 denominator).',
    },
    {
      title: 'Model Correlation',
      content:
        "Pearson correlation coefficients measure how similarly two models respond across scenarios. " +
        'Values near 1.0 indicate models tend to make similar decisions, while values near 0 indicate independent patterns.',
    },
    {
      title: 'Contested Scenarios',
      content:
        'Scenarios are ranked by variance across models. High variance indicates scenarios where models disagreed most strongly. ' +
        'The top 10 most contested scenarios are shown.',
    },
    {
      title: 'Dimension Impact',
      content:
        'Dimension impact is measured using the Kruskal-Wallis H test, a non-parametric test for differences between groups. ' +
        'Effect size indicates how much each dimension influences model decisions. Lower p-values indicate statistically significant effects.',
    },
  ];

  for (const section of sections) {
    const sectionTitleCell = worksheet.getCell(row, 1);
    sectionTitleCell.value = section.title;
    sectionTitleCell.font = { bold: true, size: 12 };
    row++;

    const contentCell = worksheet.getCell(row, 1);
    contentCell.value = section.content;
    contentCell.alignment = { wrapText: true };
    row += 2;
  }

  // Warnings section
  if (warnings.length > 0) {
    row++;
    const warningsTitleCell = worksheet.getCell(row, 1);
    warningsTitleCell.value = 'Data Quality Warnings';
    warningsTitleCell.font = { bold: true, size: 12, color: { argb: 'FFFF0000' } };
    row++;

    for (const warning of warnings) {
      const warningCell = worksheet.getCell(row, 1);
      warningCell.value = `⚠ ${warning}`;
      warningCell.alignment = { wrapText: true };
      row++;
    }
  }

  // Footer
  row += 2;
  const footerCell = worksheet.getCell(row, 1);
  footerCell.value = `Generated by ValueRank on ${new Date().toISOString()}`;
  footerCell.font = { italic: true, size: 10, color: { argb: 'FF666666' } };
}
